[package]
name = "redisearchtables"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "redisearchtables"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
